version: "3.9"
services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonize
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 172.20.0.2

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_URL: "postgres://user:postgres@172.20.0.2:5432/harmonize"
    ports:
      - "8080:8080"
    networks:
      network:
        ipv4_address: 172.20.0.3

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      API_URL: "http://172.20.0.3:8080"
    ports:
      - "5173:5173"
    networks:
      network:
        ipv4_address: 172.20.0.4

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
