version: "3.9"
services:

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonize
    volumes:
      - ./db:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_URL: "postgres://user:postgres@database:5432/harmonize"
    ports:
      - "8080:8080"
    links:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    links:
      - backend
